name: Build and test Redis jEmbedded

on:
  push:
    branches: [ main, init, '[0-9]+.x' ]
  pull_request:
    branches: [ main, init, '[0-9]+.x' ]

jobs:
  build-linux-amd64:
    runs-on: ubuntu-22.04
    env:
      OS: linux
      ARCH: amd64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: corretto
          cache: maven
      - name: build and test
        run: mvn -B verify
      - name: codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
